import { pronounSets, getPronounSet, applyPronouns, applyFeet } from './narratorSettings.js';

const NarratorLines = {
    tile: {
        forest: [
            "The trees rustle as you move beneath the forest canopy.",
            "Dappled light dances across your path in the woods.",
            "You hear distant birdsong echoing through the trees.",
            "Moss carpets the ground, muffling your footsteps.",
            "A squirrel darts up a nearby tree, chattering as it goes.",
            "Sunbeams filter through the dense leaves overhead.",
            "You catch the earthy scent of damp wood and leaves.",
            "A fallen log blocks part of the winding forest path.",
            "The air is cool and still beneath the towering trees.",
            "You spot a deer watching you quietly from the undergrowth.",
            "Twigs snap underfoot as you explore deeper into the forest.",
            "A shaft of light illuminates a patch of wild mushrooms.",
            "Birds flit between branches, their wings a blur of motion.",
            "You hear the distant tapping of a woodpecker.",
            "A fox darts between the shadows of the trees.",
            "The forest floor is littered with pinecones and leaves.",
            "You notice a family of rabbits hiding in the brush.",
            "A gentle mist hangs low among the trunks.",
            "You brush past ferns that tickle your legs.",
            "The scent of pine needles fills your senses."
        ]
    },
    nonhostileEncounter: (name) => [
        `You notice a ${name} peacefully foraging nearby.`,
        `A curious ${name} emerges from the brush, watching you with interest.`,
        `You spot a ${name} basking in the sunlight.`,
        `A gentle rustle reveals a ${name} approaching without fear.`,
        `You lock eyes with a ${name}, but it shows no sign of aggression.`,
        `A ${name} pauses to observe you, then resumes its activity.`,
        `You catch a glimpse of a ${name} moving calmly through the grass.`,
        `A ${name} stands nearby, seemingly unbothered by your presence.`,
        `You hear a soft sound and see a ${name} watching you curiously.`,
        `A ${name} appears, tail flicking in a friendly manner.`,
        `You nearly cross paths with a ${name}, but it simply nods and continues on.`,
        `A ${name} circles you at a safe distance, more curious than afraid.`,
        `You spot a ${name} relaxing in the shade.`,
        `A ${name} emerges from the undergrowth, ears perked in curiosity.`,
        `You hear a soft chirp—it's a ${name} greeting you.`,
        `A ${name} appears, eyes bright and inquisitive.`,
        `You lock eyes with a ${name}, sharing a moment of mutual respect.`,
        `A ${name} stands before you, calm and unthreatening.`,
        `You spot movement—it's a ${name} approaching with gentle steps.`,
        `A ${name} steps out from hiding, showing no fear.`,
        `You hear a quiet noise and see a ${name} nearby, simply going about its day.`
    ],
    hostileBlock: [
        "A hostile furry creature blocks your path!",
        "Something snarls and refuses to let you pass.",
        "An angry furry creature stands in your way.",
        "A menacing growl warns you not to proceed.",
        "You are confronted by a hostile furry enemy.",
        "Sharp eyes glare at you, daring you to move forward.",
        "A creature bares its teeth, blocking your advance.",
        "You sense danger as something blocks your route.",
        "A hostile presence looms ahead, unmoving.",
        "You freeze as a creature steps into your path.",
        "A sudden snarl halts your progress.",
        "You are stopped by a threatening furry.",
        "A wild beast stands between you and your destination.",
        "A low growl rumbles from the shadows ahead.",
        "You cannot continue—something dangerous blocks the way.",
        "A hostile figure refuses to let you pass.",
        "You are forced to stop by a creature's aggressive stance.",
        "A pair of glowing eyes watches you, unblinking.",
        "A threatening furry paces in front of you.",
        "You hear a hiss as your path is blocked."
    ],
    hostileEncounter: (name) => [
        `A hostile ${name} bursts onto the scene, baring its teeth!`,
        `You are confronted by a ${name} with a menacing glare.`,
        `A sudden movement reveals a ${name} ready to attack!`,
        `You come face to face with a hostile ${name}, its eyes narrowed in aggression.`,
        `A ${name} blocks your path, growling fiercely.`,
        `You hear a snarl and spot a ${name} preparing to strike.`,
        `A ${name} emerges from the shadows, posture threatening.`,
        `You lock eyes with a ${name} that looks ready to pounce.`,
        `A ${name} circles you, keeping its distance but never breaking its hostile gaze.`,
        `You sense danger as a ${name} steps into your path.`,
        `A ${name} appears suddenly, startling you with its aggression.`,
        `You notice a ${name} watching you closely, muscles tensed for battle.`,
        `A ${name} stands before you, unmoving and clearly hostile.`,
        `You catch a glimpse of a ${name} stalking you from the shadows.`,
        `A ${name} lets out a warning growl, daring you to approach.`,
        `You are forced to stop as a ${name} blocks your way, ready to fight.`,
        `A ${name} paces in front of you, eyes never leaving your own.`,
        `You hear a hiss as a ${name} prepares to defend its territory.`,
        `A ${name} lunges forward, aggression clear in every movement.`,
        `You are surrounded by the hostile presence of a ${name}.`
    ],
    hungerTooLow: [
        "You are too hungry to do that.",
        "Your stomach rumbles, preventing you from acting.",
        "Hunger weakens you too much to continue.",
        "You feel faint from hunger and can't go on.",
        "Your body refuses to move without food.",
        "You lack the strength to continue in your current state.",
        "Your vision blurs as hunger overtakes you.",
        "You clutch your stomach, too weak to act.",
        "A wave of dizziness stops you in your tracks.",
        "You try to move, but hunger holds you back.",
        "Your limbs feel heavy and unresponsive from hunger.",
        "You stagger, unable to muster the energy to proceed.",
        "Your hunger is overwhelming; you must eat first.",
        "You gasp for breath, drained by hunger.",
        "Your empty stomach aches, making action impossible.",
        "You collapse to your knees, too hungry to continue.",
        "You can barely stand, let alone act.",
        "Your body cries out for nourishment before you can do anything.",
        "You are paralyzed by hunger and unable to act.",
        "You need food before you can do anything else."
    ],
    playerDamage: () => [
        "You unleash a powerful blow, forcing your foe to stagger!",
        "Your strike lands with precision, sending shockwaves through the enemy!",
        "You attack fiercely, driving your opponent back!",
        "You swing your weapon in a wide arc, catching your foe off guard!",
        "A solid hit! The enemy reels from your assault.",
        "Your attack connects, and your opponent grunts in pain.",
        "You land a critical strike, the enemy's defenses falter!",
        "You lash out, your foe scrambling to recover.",
        "You press the attack, keeping your opponent on the defensive.",
        "Your blow lands true, the enemy stumbles from the impact.",
        "You strike swiftly, your foe barely able to react.",
        "You catch your foe off guard, forcing them to retreat a step!",
        "You deliver a punishing hit, the enemy's resolve wavering.",
        "Your weapon arcs through the air, the clash echoing across the battlefield.",
        "You drive your attack home, the enemy's guard shatters.",
        "You find an opening and exploit it, your opponent gasping in surprise.",
        "You attack with force, the enemy's stance breaking.",
        "You land a heavy blow, the foe's confidence shaken.",
        "You press your advantage, dominating the fight.",
        "You strike with determination, your enemy falters before your might."
    ],
    allyDamage: (name) => [
        `${name} launches a swift attack, catching the enemy by surprise!`,
        `${name} lands a solid blow, forcing the foe to stumble!`,
        `${name} strikes with precision, the enemy reeling from the hit!`,
        `${name} charges forward, driving the opponent back!`,
        `${name} delivers a powerful strike, the enemy's guard falters!`,
        `${name} bites down, the foe yelping in pain!`,
        `${name} slashes at the enemy, leaving them scrambling to recover!`,
        `${name} pounces, pinning the opponent momentarily!`,
        `${name} attacks fiercely, dominating the skirmish!`,
        `${name} rams into the foe, sending them sprawling!`,
        `${name} CLAWS at the opponent, forcing them to retreat!`,
        `${name} lands a critical hit, the enemy's confidence shaken!`,
        `${name} uses its strength to overpower the foe!`,
        `${name} surprises the enemy with a quick, decisive move!`,
        `${name} delivers a punishing blow, the opponent's resolve wavering!`,
        `${name} leaps into action, taking control of the fight!`,
        `${name} swings with force, the enemy's stance breaking!`,
        `${name} lunges, pressing the attack relentlessly!`,
        `${name} catches the enemy off guard, forcing them to defend desperately!`,
        `${name} presses the attack, keeping the foe on the defensive!`
    ],
    furryWounded: [
        "The furry is wounded!",
        "Your strike leaves the creature hurt!",
        "It reels back, clearly injured.",
        "The furry staggers from the blow.",
        "A pained cry escapes the creature.",
        "Blood stains the furry's FUR.",
        "The furry limps, favoring one side.",
        "You see fear in the furry's eyes.",
        "The furry snarls in pain.",
        "It struggles to keep its footing.",
        "The furry's movements slow from injury.",
        "A fresh wound marks the furry's side.",
        "The furry winces and pulls away.",
        "It bares its teeth, wounded but defiant.",
        "The furry's breathing grows ragged.",
        "You notice a deep gash on the furry's body.",
        "The furry trembles, weakened by the attack.",
        "It lets out a wounded whimper.",
        "The furry's strength is fading.",
        "The furry tries to retreat, clearly hurt."
    ],
    furryWarms: (type) => [
        `The ${type} warms up to you.`,
        `The ${type} seems less wary of you now.`,
        `You earn the ${type}'s trust.`,
        `The ${type} presses its body closer, seeking your touch.`,
        `A soft purr escapes the ${type} as it nuzzles against you.`,
        `You feel the ${type}'s breath warm against your skin.`,
        `The ${type}'s eyes glimmer with longing as it draws near.`,
        `A shiver runs through the ${type} as your hands graze its FUR.`,
        `The ${type} arches its back, inviting your caress.`,
        `You sense a deep, primal connection as the ${type} leans in.`,
        `The ${type} lets out a low, inviting growl as you approach.`,
        `Your touch elicits a soft moan from the ${type}.`,
        `The ${type} wraps itself around you, craving your warmth.`,
        `You feel the ${type}'s heartbeat quicken beneath your fingertips.`,
        `The ${type} gazes at you with smoldering intensity.`,
        `A playful nip from the ${type} sends a thrill through you both.`,
        `The ${type} trembles with anticipation as you draw closer.`,
        `You and the ${type} share a lingering, intimate moment.`,
        `The ${type} presses its lips to yours in a heated embrace.`,
        `A wave of desire passes between you and the ${type}.`,
        `The ${type} melts into your arms, surrendering to your touch.`,
        `You lose yourself in the ${type}'s passionate gaze.`,
        `The ${type} purrs deeply, inviting you to explore further.`
    ],
    playerFlirtHostileEnemy: (type, gender, plural = false) => {
        // Flirting with a hostile enemy: tension, cracks in their hostility, reluctant enjoyment
        const lines = [
            `You meet the hostile ${type}'s gaze, a daring smile on your lips. GENDER1 tries to look tough, but a smirk betrays GENDER3 amusement.`,
            `You brush your fingers along the ${type}'s arm, and GENDER1 stiffens—yet you catch a hint of shyness in GENDER2 eyes.`,
            `With a teasing grin, you lean in and whisper something that makes the ${type} bite back a smile.`,
            `You press close, letting your breath tickle the ${type}'s ear. GENDER1 pretends not to care, but you see a faint blush.`,
            `A playful wink and a gentle touch make the ${type} roll GENDER2 eyes, but GENDER1 can't hide a pleased grin.`,
            `You lock eyes with the ${type}, and for a moment, GENDER1's guard drops—just enough for you to see a flicker of warmth.`,
            `You let your hand linger on the ${type}'s side, and GENDER1 huffs, but doesn't pull away.`,
            `You murmur a sultry taunt, and the ${type} tries to scoff, but GENDER1's lips twitch with reluctant delight.`,
            `You draw the ${type} near, feeling GENDER1's resistance melt into a playful shove.`,
            `You press your body close, and the ${type} grumbles, but GENDER1's tail gives an involuntary wag.`,
            `You whisper something daring, and the ${type} snorts, but GENDER1's ears flick with interest.`,
            `You trail your fingers along the ${type}'s jaw, and GENDER1's eyes narrow, but a smile tugs at GENDER2 lips.`,
            `You lean in, your breath warm, and the ${type} tries to glare, but GENDER1's cheeks flush.`,
            `You tease the ${type} with a compliment, and GENDER1 scoffs, but can't hide a pleased look.`,
            `You nudge the ${type} playfully, and GENDER1 shoves back, but laughter escapes.`,
            `You let your hand rest on the ${type}'s chest, and GENDER1's heartbeat quickens despite GENDER4 efforts to hide it.`,
            `You murmur a secret, and the ${type} pretends not to listen, but GENDER1 leans closer.`,
            `You brush your lips near the ${type}'s ear, and GENDER1 shivers, trying to play it cool.`,
            `You compliment the ${type}'s strength, and GENDER1 puffs up, but a bashful grin slips through.`,
            `You catch the ${type} watching you, and when your eyes meet, GENDER1 quickly looks away, flustered.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    playerFlirtNonhostileEnemy: (type, gender, plural = false) => {
        // Flirting with a non-hostile enemy: curiosity, playfulness, gentle tension
        const lines = [
            `You offer the ${type} a warm smile, stepping closer as GENDER1 blushes softly.`,
            `You gently brush your hand along the ${type}'s fur, making GENDER3 shiver with anticipation.`,
            `A playful compliment makes the ${type} giggle, GENDER1 clearly enjoying your attention.`,
            `You lean in, your words soft and inviting, and the ${type} can't help but smile.`,
            `You lock eyes with the ${type}, your gaze lingering as GENDER1 looks away bashfully.`,
            `You let your fingers entwine with the ${type}'s, feeling a spark pass between you.`,
            `You whisper a sweet secret, making the ${type} perk up with interest.`,
            `You draw the ${type} into a gentle embrace, GENDER1 relaxing in your arms.`,
            `You trail a soft kiss along the ${type}'s cheek, earning a delighted sigh.`,
            `You share a quiet laugh, the air between you charged with possibility.`,
            `You nuzzle the ${type}'s neck, and GENDER1 giggles, leaning into your touch.`,
            `You compliment the ${type}'s eyes, and GENDER1 beams with pride.`,
            `You playfully bump shoulders with the ${type}, and GENDER1 laughs, bumping you back.`,
            `You whisper a joke, and the ${type} bursts into laughter, GENDER1's tail wagging.`,
            `You brush a stray lock of fur from the ${type}'s face, and GENDER1 smiles shyly.`,
            `You offer your hand, and the ${type} takes it, fingers squeezing yours gently.`,
            `You share a secret glance, and GENDER1's cheeks flush with excitement.`,
            `You tease the ${type} with a flirty remark, and GENDER1 grins, clearly enjoying the attention.`,
            `You lean in for a playful peck, and the ${type} returns it with a bashful giggle.`,
            `You and the ${type} share a moment of quiet closeness, the world fading away.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    playerFlirtAlly: (name, gender, plural = false) => {
        // Flirting with an ally: trust, affection, shared history
        const lines = [
            `You catch ${name}'s eye and flash a mischievous grin, making GENDER1 laugh.`,
            `You lean against ${name}, your touch familiar and welcome.`,
            `A whispered joke in ${name}'s ear makes GENDER1 blush and nudge you playfully.`,
            `You entwine your fingers with ${name}'s, sharing a moment of quiet affection.`,
            `You press your lips to ${name}'s cheek, feeling GENDER2 warmth radiate back.`,
            `You share a lingering look with ${name}, memories and feelings passing unspoken between you.`,
            `You draw ${name} close, your arms wrapping around GENDER3 in a gentle hug.`,
            `You tease ${name} with a playful wink, earning a soft laugh.`,
            `You rest your head on ${name}'s shoulder, feeling safe and content.`,
            `You and ${name} share a private smile, the bond between you clear to anyone watching.`,
            `You ruffle ${name}'s hair, and GENDER1 grins, swatting your hand away playfully.`,
            `You whisper a compliment, and ${name} beams with pride.`,
            `You bump hips with ${name}, and GENDER1 laughs, bumping you back.`,
            `You share a secret glance, and GENDER1's cheeks flush with affection.`,
            `You offer your hand, and ${name} squeezes it gently.`,
            `You nuzzle into ${name}'s neck, and GENDER1 giggles, hugging you tighter.`,
            `You share a silly inside joke, and both of you burst into laughter.`,
            `You lean in for a playful peck, and ${name} returns it with a bashful smile.`,
            `You and ${name} share a moment of quiet closeness, the world fading away.`,
            `You rest your forehead against ${name}'s, savoring the warmth between you.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },

    // === Ally Actions Against Enemies ===
    allyFlirtEnemy: (allyName, enemyName, gender, plural = false) => {
        // Ally flirting with enemy: mysterious, primal, forest-themed
        const lines = [
            `${allyName} emerges from behind a massive oak, approaching ${enemyName} with feline grace. GENDER1 trails GENDER3 fingers along bark-covered trees, the dappled sunlight highlighting GENDER3 alluring silhouette as GENDER1 moves through shadow and light.`,
            `${allyName} uses the forest's natural cover, appearing and disappearing between ancient trunks as GENDER1 circles ${enemyName}. GENDER3 playful game of hide-and-seek among the towering trees creates an atmosphere of thrilling anticipation.`,
            `${allyName} finds a fallen log and perches gracefully upon it, beckoning ${enemyName} with a mysterious smile. GENDER3 eyes gleam like moonlight through the canopy as GENDER1 pats the moss-covered wood beside GENDER2 invitingly.`,
            `${allyName} gathers a handful of autumn leaves and lets them flutter down around ${enemyName}, each colorful piece dancing through the filtered sunlight. "Beautiful things fall for beautiful beings," GENDER1 whispers with a knowing grin.`,
            `${allyName} leans against an ancient tree, GENDER3 pose deliberately casual yet seductive. GENDER1 traces patterns in the bark with one finger while maintaining eye contact with ${enemyName}, the forest's whispers seeming to echo GENDER3 silent invitation.`,
            `${allyName} discovers a fairy ring of mushrooms and steps into its center, extending GENDER3 hand toward ${enemyName}. "Dance with me in this enchanted circle," GENDER1 purrs, GENDER3 voice mixing with the forest's mysterious song.`,
            `${allyName} climbs onto a low branch with fluid grace, dangling upside down to meet ${enemyName} at eye level. GENDER3 playful acrobatics and mischievous grin among the swaying leaves create an irresistible charm.`,
            `${allyName} follows a winding deer path, glancing back at ${enemyName} with sultry eyes. GENDER1 moves deeper into the forest's embrace, each step a tantalizing invitation to follow GENDER2 into the green cathedral.`,
            `${allyName} finds a stream trickling through the forest and kneels beside it, cupping the clear water. GENDER1 offers it to ${enemyName} with both hands, the intimate gesture framed by ferns and reflected in the babbling brook.`,
            `${allyName} weaves between the ancient trees like a forest spirit, GENDER3 movements hypnotic and wild. GENDER1 pauses within a shaft of golden sunlight, letting it illuminate GENDER3 form as GENDER1 beckons ${enemyName} into the woodland's depths.`
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },

    allyFeastSuccess: (allyName, enemyType) => [
        `${allyName} strikes from the shadows between towering trees, the ${enemyType} unable to escape through the dense undergrowth. The hunt ends swiftly among the fallen leaves as ${allyName} claims GENDER3 forest prize.`,
        `${allyName} uses the woodland's natural maze to corner the ${enemyType} against a massive trunk. The ancient trees witness GENDER3 successful hunt as GENDER1 satisfies GENDER3 primal hunger among the moss and ferns.`,
        `${allyName} moves through the forest canopy with predatory grace, dropping down onto the unsuspecting ${enemyType}. The thick carpet of leaves muffles the brief struggle as ${allyName} emerges victorious.`,
        `${allyName} stalks silently through the dappled shadows, the ${enemyType} unaware until it's too late. The forest keeps GENDER3 secrets as ${allyName} drags GENDER3 feast deeper into the woodland's protective embrace.`,
        `${allyName} herds the ${enemyType} through winding deer paths, using GENDER3 knowledge of the forest to trap them in a clearing. The hunt concludes among wildflowers as ${allyName} claims GENDER3 woodland victory.`,
        `${allyName} pounces from behind a curtain of hanging vines, the ${enemyType} caught completely off-guard. The brief chase through the undergrowth ends with ${allyName} triumphant beneath the forest canopy.`,
        `${allyName} uses the forest's natural obstacles to GENDER3 advantage, driving the ${enemyType} toward a steep ravine. Trapped between earth and sky, the prey becomes ${allyName}'s well-earned meal.`,
        `${allyName} emerges from a thicket of brambles, thorns tangled in GENDER3 fur but hunger blazing in GENDER3 eyes. The ${enemyType} flees deeper into the woods, but there's no escape from ${allyName}'s forest hunt.`
    ],

    allyFeastFail: (allyName, enemyType) => [
        `${allyName} lunges through the undergrowth, but the ${enemyType} scrambles up a tree faster than lightning. GENDER1 circles the trunk in frustration as GENDER3 prey remains safely perched among the branches.`,
        `${allyName} gives chase through the forest, but the ${enemyType} knows these woods better than expected. They vanish into a hidden burrow beneath gnarled roots, leaving ${allyName} empty-handed among the ferns.`,
        `${allyName} attempts to corner the ${enemyType}, but steps on a branch that snaps loudly. The sound echoes through the trees, alerting every creature as the prey bolts toward the safety of dense brambles.`,
        `${allyName} pursues the ${enemyType} through winding paths, but gets tangled in hanging vines. By the time GENDER1 breaks free, GENDER3 prey has vanished into the forest's green labyrinth.`,
        `${allyName} tracks the ${enemyType} to a stream, but the clever prey uses the water to mask their scent. GENDER1 loses the trail among the babbling brooks and moss-covered stones.`,
        `${allyName} climbs high into the canopy for a better view, but the ${enemyType} uses the distraction to disappear into a hollow log. The forest swallows them whole, leaving ${allyName} frustrated above.`,
        `${allyName} attempts to drive the ${enemyType} into the open, but startles a flock of birds instead. The cacophony of wings and cries creates enough chaos for the prey to slip away unnoticed.`
    ],

    allyFeedSuccess: (allyName, enemyType) => [
        `${allyName} discovers a grove of berry bushes and gathers the sweetest fruits to share with the ${enemyType}. The forest's bounty and GENDER3 generous heart win over the cautious creature completely.`,
        `${allyName} finds a clear spring hidden among the trees and offers its pure water to the thirsty ${enemyType}. This act of kindness in the forest's sacred space creates an unbreakable bond of trust.`,
        `${allyName} weaves a crown of ferns and wildflowers, placing it gently on the ${enemyType}'s head. The beautiful gift, crafted from the forest's treasures, melts away all suspicion and fear.`,
        `${allyName} demonstrates the forest's safety by resting peacefully against an ancient oak, showing the ${enemyType} that danger has passed. The tree's protective presence convinces them to join your group.`,
        `${allyName} collects smooth river stones and arranges them in a peaceful pattern, inviting the ${enemyType} to add their own. This simple act of creation together among the trees builds lasting friendship.`,
        `${allyName} finds a fallen log rich with edible mushrooms and shares them freely with the ${enemyType}. The forest's hidden feast proves GENDER3 good intentions and generous nature.`,
        `${allyName} leads the ${enemyType} to a sunlit clearing where butterflies dance among wildflowers. The magical spot's beauty and ${allyName}'s gentle guidance create perfect trust and harmony.`,
        `${allyName} shows the ${enemyType} how to read the forest's signs - which berries are safe, where fresh water flows. This shared knowledge creates a bond deeper than mere alliance.`
    ],

    allyFeedFail: (allyName, enemyType) => [
        `${allyName} offers gathered berries to the ${enemyType}, but accidentally includes some bitter ones. The poor taste ruins the gesture, sending the ${enemyType} fleeing deeper into the protective woods.`,
        `${allyName} tries to share forest wisdom with the ${enemyType}, but a falling pinecone bonks GENDER2 on the head mid-sentence. The embarrassing moment destroys any credibility GENDER1 had built.`,
        `${allyName} attempts to create a peaceful atmosphere by singing to the birds, but GENDER3 voice scares them away instead. The ${enemyType} takes this as a bad omen and retreats into the shadows.`,
        `${allyName} leads the ${enemyType} to a beautiful grove, but disturbs a wasp nest along the way. The angry swarm sends both creatures scrambling, ruining any chance of friendship.`,
        `${allyName} tries to impress the ${enemyType} with GENDER3 tree-climbing skills, but slips and crashes down through the branches. The undignified tumble leaves the ${enemyType} unimpressed and wary.`,
        `${allyName} gathers flowers for the ${enemyType}, but chooses ones that trigger their allergies. The sneezing fit that follows makes meaningful conversation impossible in the woodland setting.`,
        `${allyName} attempts to demonstrate forest harmony by communing with a deer, but the startled animal bounds away, knocking over both ${allyName} and the ${enemyType} in its panic.`
    ],

    allyFuckSuccess: (allyName, enemyType, gender, plural = false) => [
        `${allyName} and the ${enemyType} find privacy in a grove where ancient trees form natural walls. Surrounded by the forest's protective embrace, they explore their desires beneath a canopy of leaves, their passion echoing softly through the woods.`,
        `${allyName} leads the ${enemyType} to a moss-covered clearing where shafts of sunlight create a natural cathedral. Here, among ferns and wildflowers, they share an intimate connection as old and deep as the forest itself.`,
        `${allyName} and the ${enemyType} discover each other on a bed of fallen leaves, the forest floor soft and welcoming beneath them. Their encounter is wild yet tender, witnessed only by the swaying trees above.`,
        `${allyName} creates a bower of woven branches and soft moss for GENDER3 and the ${enemyType} to share. In this natural sanctuary, they find pleasure in each other's arms, the forest blessing their union with whispered songs.`,
        `${allyName} and the ${enemyType} curl together beside a babbling brook, the water's melody enhancing their intimate dance. The forest's ancient magic seems to flow through them, deepening their connection.`,
        `${allyName} guides the ${enemyType} up into the branches of a massive oak, where they find a hollow lined with soft bark. High above the forest floor, they share passion that reaches toward the stars.`,
        `${allyName} and the ${enemyType} meet in a fairy ring where mushrooms glow with ethereal light. Their coupling in this mystical circle feels touched by forest magic, leaving them both transformed.`,
        `${allyName} shows the ${enemyType} a hidden grove where deer come to drink, but now it becomes their private sanctuary. Among the peaceful spirits of the woodland, they discover ecstasy in each other's embrace.`
    ],

    allyFuckFail: (allyName, enemyType) => [
        `${allyName} and the ${enemyType} settle into a cozy hollow, but a family of squirrels has the same idea. The chattering rodents refuse to leave, making intimacy impossible in the contested tree space.`,
        `${allyName} tries to create romance beneath a beautiful flowering tree, but discovers too late it's home to a beehive. The angry buzzing sends both creatures fleeing before anything intimate can happen.`,
        `${allyName} and the ${enemyType} find a mossy spot that seems perfect, but it turns out to be directly above a rabbit warren. The ground collapses beneath them, ruining the mood completely.`,
        `${allyName} attempts to impress the ${enemyType} by climbing to a romantic tree hollow, but gets stuck halfway up. GENDER3 undignified predicament kills any passion the ${enemyType} might have felt.`,
        `${allyName} and the ${enemyType} begin to connect beside a peaceful stream, but a sudden downpour turns their romantic spot into a muddy mess. They end up cold, wet, and thoroughly un-romantic.`,
        `${allyName} tries to create atmosphere by howling softly at the moon, but accidentally triggers a response from every wolf in the forest. The cacophony makes intimate conversation impossible.`,
        `${allyName} and the ${enemyType} settle onto what they think is soft moss, but it's actually a patch of stinging nettles. The painful discovery sends them hopping away, all thoughts of romance forgotten.`
    ],

    furryInterested: (type) => [
        `The ${type} seems interested...`,
        `You notice a spark of curiosity in its eyes.`,
        `It appears intrigued by you.`,
        `The ${type} tilts its head, watching you closely.`,
        `A soft sound escapes the ${type} as it draws nearer.`,
        `You catch the ${type} glancing at you repeatedly.`,
        `It circles you, sniffing the air with interest.`,
        `The ${type}'s EARS perk up as you approach.`,
        `You sense the ${type}'s attention is fixed on you.`,
        `It takes a cautious step in your direction.`,
        `The ${type}'s TAIL flicks with anticipation.`,
        `You see the ${type}'s NOSE twitch as it studies you.`,
        `It sits down, waiting to see what you'll do next.`,
        `The ${type}'s eyes follow your every movement.`,
        `It lets out a curious chirp or grunt.`,
        `You feel the ${type}'s gaze linger on you.`,
        `It edges closer, clearly wanting to learn more.`,
        `The ${type} sniffs at your hand, testing your scent.`,
        `It gives a tentative wag or purr.`,
        `You notice the ${type}'s body language relax slightly.`
    ],
    feastSuccess: (type, gain) => [
        `You feast on the ${type} and gain ${gain} hunger!`,
        `Devouring the ${type} restores ${gain} hunger!`,
        `You consume the ${type}, replenishing ${gain} hunger.`,
        `You open wide and swallow the ${type} whole, feeling your hunger fade as it settles inside.`,
        `The ${type} squirms as you gulp it down, your belly growing fuller with every swallow.`,
        `With a deep breath, you engulf the ${type}, its struggles fading as you digest it for ${gain} hunger.`,
        `You savor the sensation as the ${type} slides down your throat, nourishing you from within.`,
        `The ${type} vanishes into your MAW, leaving you satisfied and energized.`,
        `You feel the ${type} wriggle as it descends, your hunger replaced by a pleasant fullness.`,
        `A powerful gulp sends the ${type} into your stomach, where it fuels your strength.`,
        `You relish the fullness as the ${type} is safely tucked away inside you.`,
        `The ${type} is enveloped by your body, its energy becoming your own.`,
        `You pat your belly contentedly after swallowing the ${type} whole.`,
        `The ${type} disappears past your lips, and you feel a surge of vitality.`,
        `You draw the ${type} in, your hunger quickly fading as you digest your living meal.`,
        `The ${type} is helpless as you swallow it, your body eagerly absorbing its energy.`,
        `You gulp down the ${type}, feeling it settle and your hunger vanish.`,
        `A deep sense of satisfaction washes over you as the ${type} is vored alive.`,
        `You feel the ${type} moving inside for a moment before your hunger is fully sated.`,
        `The ${type} is drawn into your stomach, its presence fueling your recovery.`,
        `You finish your meal, the ${type} now a part of you, and your hunger gone.`,
        `You swallow the ${type} in one smooth motion, feeling stronger immediately.`,
        `The ${type} is enveloped by your MAW, and you feel your hunger melt away.`,
        `You savor the living meal, the ${type} nourishing you as it disappears inside.`,
        `You feel the ${type}'s energy flow into you as you finish your feast.`,
        `The ${type} is gone, leaving you feeling full and revitalized.`,
        `You take a moment to enjoy the sensation as the ${type} is digested alive.`,
        `You feel your strength return as the ${type} is absorbed within you.`,
        `The ${type} is swallowed whole, and you feel completely satisfied.`
    ],
    feastFail: (type) => [
        `Your feast attempt fails.`,
        `You fail to satisfy your hunger.`,
        `The ${type} slips from your grasp.`,
        `You miss your chance to swallow the ${type}.`,
        `Your prey escapes before you can feast.`,
        `You fumble and lose the ${type}.`,
        `Your hunger remains as the ${type} wiggles out of your PAWS.`,
        `You bite down, but the ${type} wriggles free.`,
        `You hesitate, and the opportunity is lost.`,
        `You can't quite manage to eat the ${type} this time.`,
        `Your MAW snaps shut on empty air.`,
        `You lunge, but your ${type} gets away.`,
        `You try to feast on the ${type}, but you fail.`,
        `You lose your grip and the ${type} escapes.`,
        `Your attempt is thwarted by a sudden movement.`,
        `You are left hungry as your ${type} flees.`,
        `You feel frustration as the ${type} dodges your grasp.`,
        `You watch helplessly as the ${type} slips away.`,
        `Your belly gurgles as you fail to swallow the ${type}.`,
        `${type} escapes your grasp at the last moment.`
    ],
    recruitSuccess: (type) => [
        `You successfully recruit the ${type}!`,
        `The ${type} joins your cause!`,
        `You gain a new ally: the ${type}.`,
        `The ${type} is now part of your team.`,
        `With a nod, the ${type} agrees to follow you.`,
        `The ${type} pledges loyalty to your journey.`,
        `A new friendship is forged with the ${type}.`,
        `The ${type} stands proudly at your side.`,
        `You welcome the ${type} into your ranks.`,
        `The ${type} is eager to help you on your quest.`,
        `A sense of camaraderie grows as the ${type} joins you.`,
        `The ${type} is ready to face challenges with you.`,
        `You feel stronger with the ${type} as your ally.`,
        `The ${type} gives a cheerful nod, ready for adventure.`,
        `The ${type} is happy to be part of your group.`,
        `You and the ${type} share a moment of mutual respect.`,
        `The ${type} is now a trusted companion.`,
        `The ${type} steps forward, accepting your invitation.`,
        `A bond forms as the ${type} joins your side.`,
        `The ${type} is now a valued member of your party.`,
        `You sense the ${type}'s determination to help you succeed.`
    ],
    allyMadeOut: (type, gender, plural = false) => {
        // Use GENDER# placeholders in lines
        const lines = [
            `${type} kisses you passionately, breathless kiss, hands roaming hungrily over each other's bodies.`,
            `${type} presses against your body with lust in GENDER2 eyes, GENDER1 throws you on the ground, and you both make out.`,
            `You both explore each other's body, moans and gasps filling the air.`,
            `You lock paws with ${type}, bodies entwined as you kiss deeply.`,
            `${type} gently pushes you against a tree, kissing you passionately.`,
            `You both pull eachother close, bodies pressed tightly, feeling every curve and muscle as you kiss deeply.`,
            `${type} pulls you to the ground, kissing you passionately.`,
            `You both lean into each other, shivering with anticipation as lips and tongues explore sensitive spots.`,
            `One bites gently at the other's lower lip, drawing a gasp before diving into another passionate kiss.`,
            `You lose yourself in ${type}'s passionate kisses, hands and mouths exploring, breath mingling in the heat.`,
            `Your fingers trace along GENDER2 skin, sending shivers as they press closer, desperate for more contact.`,
            `${type}'s hand slides down, gripping a thigh and pulling their bodies even tighter.`,
            `You both roll on the ground, tangled in limbs and laughter, lips never parting for long.`,
            `A teasing tongue flicks along your lips before diving into a deep, passionate kiss.`,
            `${type}'s kisses grow deeper, more urgent, as hands roam and bodies grind together.`,
            `You both gasp each other's names, lost in the haze of pleasure and longing.`,
            `${type} pins you to the ground, lips trailing down your neck as GENDER2 hands explore boldly.`,
            `You both arch and writhe together, every touch and kiss stoking the fire between you.`,
            `Breathless and flushed, you cling to each other, savoring every heated moment.`,
            `Your bodies move in perfect rhythm, lost in the intensity of your embrace.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    actionFail: [
        "Your attempt fails.",
        "That didn't work.",
        "You don't manage to pull it off.",
        "You fumble and lose your chance.",
        "Your hands slip at the last moment.",
        "You hesitate, and the opportunity passes.",
        "You try, but nothing happens.",
        "You misjudge your timing and fail.",
        "You lose focus and the action slips away.",
        "You make a mistake and it doesn't work.",
        "You stumble, ruining your attempt.",
        "You can't seem to get it right.",
        "You miss your mark.",
        "You act, but the result is disappointing.",
        "You give it your best, but fall short.",
        "You try again, but still fail.",
        "You are thwarted by bad luck.",
        "You falter and the action fizzles.",
        "You attempt it, but something goes wrong.",
        "You are unable to complete the action."
    ],
    enemyHitPlayer: (type) => [
        `The ${type} hits you with a fierce blow!`,
        `You are struck by the ${type}, pain radiating through your body!`,
        `Ouch! The ${type}'s attack leaves you reeling.`,
        `A sudden blow from the ${type} knocks you off balance!`,
        `The ${type} lashes out, forcing you to defend yourself!`,
        `You feel pain as the ${type} attacks relentlessly.`,
        `The ${type}'s attack lands, making you stagger!`,
        `You stagger as the ${type} lands a solid hit.`,
        `A sharp strike from the ${type} makes you wince.`,
        `The ${type} CLAWS at you, tearing at your defenses!`,
        `You wince as the ${type} bites down hard.`,
        `A heavy blow from the ${type} sends you stumbling!`,
        `The ${type} rams into you, knocking the wind from your lungs.`,
        `You are knocked back by the ${type}'s powerful attack.`,
        `The ${type} pounces, pinning you momentarily!`,
        `You feel the sting of the ${type}'s relentless assault.`,
        `A quick swipe from the ${type} leaves a burning pain!`,
        `The ${type} lands a solid hit, your vision blurring for a moment.`,
        `You are wounded by the ${type}, struggling to stay upright.`,
        `The ${type} strikes fiercely, your strength faltering.`,
        `You are battered by the ${type}'s unyielding assault.`
    ],
    enemyHitAlly: (type, name) => [
        `The ${type} hits ${name} with a fierce blow!`,
        `${name} is struck by the ${type}, reeling from the impact!`,
        `${name} is knocked back by the ${type}'s attack!`,
        `${name} takes a blow from the ${type}, struggling to stay upright!`,
        `A fierce attack from the ${type} leaves ${name} staggering!`,
        `${name} is wounded by the ${type}, faltering in the fight!`,
        `The ${type} CLAWS at ${name}, tearing at their defenses!`,
        `${name} winces as the ${type} lands a solid hit.`,
        `A sudden strike from the ${type} leaves ${name} off balance.`,
        `${name} is battered by the ${type}, barely holding on!`,
        `The ${type} bites down on ${name}, making them cry out!`,
        `${name} is knocked back by the ${type}'s powerful attack!`,
        `A heavy blow from the ${type} leaves ${name} hurt and dazed.`,
        `${name} is caught off guard and takes a punishing hit from the ${type}.`,
        `The ${type} pounces on ${name}, pinning them momentarily!`,
        `${name} suffers under the ${type}'s relentless assault!`,
        `A quick swipe from the ${type} leaves ${name} scrambling to recover!`,
        `${name} staggers as the ${type} delivers a crushing blow!`,
        `The ${type} rams into ${name}, sending them sprawling!`,
        `${name} is wounded by a sudden attack from the ${type}, struggling to regain composure!`
    ],
    enemyFled: (type) => [
        `The ${type} fled!`,
        `The ${type} escapes into the distance!`,
        `With a quick dash, the ${type} is gone.`,
        `The ${type} vanishes into the undergrowth.`,
        `You watch as the ${type} disappears from sight.`,
        `The ${type} bolts away, leaving you behind.`,
        `A flash of movement, and the ${type} is gone.`,
        `The ${type} retreats hastily, not looking back.`,
        `You see only a blur as the ${type} flees.`,
        `The ${type} darts away, evading your grasp.`,
        `The ${type} slips away before you can react.`,
        `You lose sight of the ${type} as it escapes.`,
        `The ${type} sprints off, quickly out of reach.`,
        `A rustle in the brush marks the ${type}'s escape.`,
        `The ${type} makes a hasty retreat.`,
        `You hear the sound of the ${type} running away.`,
        `The ${type} vanishes between the trees.`,
        `The ${type} flees, leaving only footprints behind.`,
        `You catch a glimpse of the ${type} as it disappears.`,
        `The ${type} runs for safety, not daring to look back.`
    ],
    enemyFleeFail: (type) => [
        `The ${type} tried to flee but failed.`,
        `The ${type} attempts escape and stumbles!`,
        `Escape fails for the ${type}.`,
        `The ${type} tries to run but is blocked!`,
        `The ${type} makes a break for it, but can't get away.`,
        `The ${type} darts to the side, but you cut it off.`,
        `The ${type} hesitates and loses its chance to escape.`,
        `A failed leap leaves the ${type} vulnerable.`,
        `The ${type} slips but can't get away in time.`,
        `The ${type} turns to flee, but is stopped short.`,
        `The ${type} is too slow and fails to escape.`,
        `The ${type} panics, but can't find a way out.`,
        `The ${type} is cornered and cannot flee.`,
        `The ${type} tries to vanish, but you block its path.`,
        `The ${type} is trapped and its escape fails.`,
        `The ${type} looks for an exit, but finds none.`,
        `The ${type} is thwarted in its attempt to flee.`,
        `The ${type} makes a desperate dash, but is caught.`,
        `The ${type} is forced to stay and fight.`,
        `The ${type} freezes, unable to escape.`
    ],
    playerFleeFail: (type) => [
        `Failed to flee!`,
        `You can't get away!`,
        `Your escape attempt is thwarted.`,
        `You try to run, but the ${type} blocks your path.`,
        `You stumble and lose your chance to escape.`,
        `You hesitate, and the ${type} closes in.`,
        `You turn to flee, but your legs won't move.`,
        `A sudden obstacle stops you from escaping.`,
        `You dash for safety, but are forced back.`,
        `You slip and fall, unable to get away.`,
        `Your path is blocked and you can't escape.`,
        `You make a break for it, but are intercepted.`,
        `You freeze in fear and fail to flee.`,
        `You try to slip away, but are spotted instantly.`,
        `You attempt to retreat, but the way is shut.`,
        `You are too slow and the ${type} catches up.`,
        `You look for an exit, but find none.`,
        `You try to vanish into the shadows, but are seen.`,
        `You dart to the side, but are cut off.`,
        `You attempt to escape, but your efforts are in vain.`
    ],
};

function narrateTile(tile) {
    const lines = NarratorLines.tile[tile];
    if (Array.isArray(lines) && lines.length > 0) {
        const line = lines[Math.floor(Math.random() * lines.length)];
        updateNarrator(line);
    }
}
export default NarratorLines;