import { pronounSets, getPronounSet, applyPronouns, applyFeet } from './narratorSettings.js';

const NarratorLines = {
    tile: {
        pond: [
            "Water laps quietly as you near the tranquil pond.",
            "A cool breeze ripples the surface of the water.",
            "The pond reflects the sky like a mirror.",
            "Dragonflies dart above the still pond water.",
            "You spot lily pads floating serenely on the surface.",
            "A frog croaks from the pond's edge.",
            "Tiny fish dart beneath the clear water.",
            "Reeds sway gently along the pond's border.",
            "You catch your reflection shimmering in the pond.",
            "A duck glides silently across the pond.",
            "Ripples spread as something breaks the surface.",
            "The air is thick with the scent of fresh water.",
            "Sunlight sparkles on the pond's gentle waves.",
            "A turtle basks on a sun-warmed rock.",
            "You hear the plop of something diving underwater.",
            "A water strider skims across the pond's surface.",
            "You notice tadpoles wriggling near the shore.",
            "The pond is ringed with blooming water lilies.",
            "A gentle splash startles a flock of birds into flight.",
            "You spot a heron standing motionless at the water's edge."
        ]
    },
    nonhostileEncounter: (name) => [
        `You notice a ${name} peacefully foraging nearby.`,
        `A curious ${name} emerges from the brush, watching you with interest.`,
        `You spot a ${name} basking in the sunlight.`,
        `A gentle rustle reveals a ${name} approaching without fear.`,
        `You lock eyes with a ${name}, but it shows no sign of aggression.`,
        `A ${name} pauses to observe you, then resumes its activity.`,
        `You catch a glimpse of a ${name} moving calmly through the grass.`,
        `A ${name} stands nearby, seemingly unbothered by your presence.`,
        `You hear a soft sound and see a ${name} watching you curiously.`,
        `A ${name} appears, tail flicking in a friendly manner.`,
        `You nearly cross paths with a ${name}, but it simply nods and continues on.`,
        `A ${name} circles you at a safe distance, more curious than afraid.`,
        `You spot a ${name} relaxing in the shade.`,
        `A ${name} emerges from the undergrowth, ears perked in curiosity.`,
        `You hear a soft chirp—it's a ${name} greeting you.`,
        `A ${name} appears, eyes bright and inquisitive.`,
        `You lock eyes with a ${name}, sharing a moment of mutual respect.`,
        `A ${name} stands before you, calm and unthreatening.`,
        `You spot movement—it's a ${name} approaching with gentle steps.`,
        `A ${name} steps out from hiding, showing no fear.`,
        `You hear a quiet noise and see a ${name} nearby, simply going about its day.`
    ],
    hostileBlock: [
        "A hostile furry creature blocks your path!",
        "Something snarls and refuses to let you pass.",
        "An angry furry creature stands in your way.",
        "A menacing growl warns you not to proceed.",
        "You are confronted by a hostile furry enemy.",
        "Sharp eyes glare at you, daring you to move forward.",
        "A creature bares its teeth, blocking your advance.",
        "You sense danger as something blocks your route.",
        "A hostile presence looms ahead, unmoving.",
        "You freeze as a creature steps into your path.",
        "A sudden snarl halts your progress.",
        "You are stopped by a threatening furry.",
        "A wild beast stands between you and your destination.",
        "A low growl rumbles from the shadows ahead.",
        "You cannot continue—something dangerous blocks the way.",
        "A hostile figure refuses to let you pass.",
        "You are forced to stop by a creature's aggressive stance.",
        "A pair of glowing eyes watches you, unblinking.",
        "A threatening furry paces in front of you.",
        "You hear a hiss as your path is blocked."
    ],
    hostileEncounter: (name) => [
        `A hostile ${name} bursts onto the scene, baring its teeth!`,
        `You are confronted by a ${name} with a menacing glare.`,
        `A sudden movement reveals a ${name} ready to attack!`,
        `You come face to face with a hostile ${name}, its eyes narrowed in aggression.`,
        `A ${name} blocks your path, growling fiercely.`,
        `You hear a snarl and spot a ${name} preparing to strike.`,
        `A ${name} emerges from the shadows, posture threatening.`,
        `You lock eyes with a ${name} that looks ready to pounce.`,
        `A ${name} circles you, keeping its distance but never breaking its hostile gaze.`,
        `You sense danger as a ${name} steps into your path.`,
        `A ${name} appears suddenly, startling you with its aggression.`,
        `You notice a ${name} watching you closely, muscles tensed for battle.`,
        `A ${name} stands before you, unmoving and clearly hostile.`,
        `You catch a glimpse of a ${name} stalking you from the shadows.`,
        `A ${name} lets out a warning growl, daring you to approach.`,
        `You are forced to stop as a ${name} blocks your way, ready to fight.`,
        `A ${name} paces in front of you, eyes never leaving your own.`,
        `You hear a hiss as a ${name} prepares to defend its territory.`,
        `A ${name} lunges forward, aggression clear in every movement.`,
        `You are surrounded by the hostile presence of a ${name}.`
    ],
    hungerTooLow: [
        "You are too hungry to do that.",
        "Your stomach rumbles, preventing you from acting.",
        "Hunger weakens you too much to continue.",
        "You feel faint from hunger and can't go on.",
        "Your body refuses to move without food.",
        "You lack the strength to continue in your current state.",
        "Your vision blurs as hunger overtakes you.",
        "You clutch your stomach, too weak to act.",
        "A wave of dizziness stops you in your tracks.",
        "You try to move, but hunger holds you back.",
        "Your limbs feel heavy and unresponsive from hunger.",
        "You stagger, unable to muster the energy to proceed.",
        "Your hunger is overwhelming; you must eat first.",
        "You gasp for breath, drained by hunger.",
        "Your empty stomach aches, making action impossible.",
        "You collapse to your knees, too hungry to continue.",
        "You can barely stand, let alone act.",
        "Your body cries out for nourishment before you can do anything.",
        "You are paralyzed by hunger and unable to act.",
        "You need food before you can do anything else."
    ],
    playerDamage: () => [
        "You unleash a powerful blow, forcing your foe to stagger!",
        "Your strike lands with precision, sending shockwaves through the enemy!",
        "You attack fiercely, driving your opponent back!",
        "You swing your weapon in a wide arc, catching your foe off guard!",
        "A solid hit! The enemy reels from your assault.",
        "Your attack connects, and your opponent grunts in pain.",
        "You land a critical strike, the enemy's defenses falter!",
        "You lash out, your foe scrambling to recover.",
        "You press the attack, keeping your opponent on the defensive.",
        "Your blow lands true, the enemy stumbles from the impact.",
        "You strike swiftly, your foe barely able to react.",
        "You catch your foe off guard, forcing them to retreat a step!",
        "You deliver a punishing hit, the enemy's resolve wavering.",
        "Your weapon arcs through the air, the clash echoing across the battlefield.",
        "You drive your attack home, the enemy's guard shatters.",
        "You find an opening and exploit it, your opponent gasping in surprise.",
        "You attack with force, the enemy's stance breaking.",
        "You land a heavy blow, the foe's confidence shaken.",
        "You press your advantage, dominating the fight.",
        "You strike with determination, your enemy falters before your might."
    ],
    allyDamage: (name) => [
        `${name} launches a swift attack, catching the enemy by surprise!`,
        `${name} lands a solid blow, forcing the foe to stumble!`,
        `${name} strikes with precision, the enemy reeling from the hit!`,
        `${name} charges forward, driving the opponent back!`,
        `${name} delivers a powerful strike, the enemy's guard falters!`,
        `${name} bites down, the foe yelping in pain!`,
        `${name} slashes at the enemy, leaving them scrambling to recover!`,
        `${name} pounces, pinning the opponent momentarily!`,
        `${name} attacks fiercely, dominating the skirmish!`,
        `${name} rams into the foe, sending them sprawling!`,
        `${name} CLAWS at the opponent, forcing them to retreat!`,
        `${name} lands a critical hit, the enemy's confidence shaken!`,
        `${name} uses its strength to overpower the foe!`,
        `${name} surprises the enemy with a quick, decisive move!`,
        `${name} delivers a punishing blow, the opponent's resolve wavering!`,
        `${name} leaps into action, taking control of the fight!`,
        `${name} swings with force, the enemy's stance breaking!`,
        `${name} lunges, pressing the attack relentlessly!`,
        `${name} catches the enemy off guard, forcing them to defend desperately!`,
        `${name} presses the attack, keeping the foe on the defensive!`
    ],
    furryWounded: [
        "The furry is wounded!",
        "Your strike leaves the creature hurt!",
        "It reels back, clearly injured.",
        "The furry staggers from the blow.",
        "A pained cry escapes the creature.",
        "Blood stains the furry's FUR.",
        "The furry limps, favoring one side.",
        "You see fear in the furry's eyes.",
        "The furry snarls in pain.",
        "It struggles to keep its footing.",
        "The furry's movements slow from injury.",
        "A fresh wound marks the furry's side.",
        "The furry winces and pulls away.",
        "It bares its teeth, wounded but defiant.",
        "The furry's breathing grows ragged.",
        "You notice a deep gash on the furry's body.",
        "The furry trembles, weakened by the attack.",
        "It lets out a wounded whimper.",
        "The furry's strength is fading.",
        "The furry tries to retreat, clearly hurt."
    ],
    furryWarms: (type) => [
        `The ${type} warms up to you.`,
        `The ${type} seems less wary of you now.`,
        `You earn the ${type}'s trust.`,
        `The ${type} presses its body closer, seeking your touch.`,
        `A soft purr escapes the ${type} as it nuzzles against you.`,
        `You feel the ${type}'s breath warm against your skin.`,
        `The ${type}'s eyes glimmer with longing as it draws near.`,
        `A shiver runs through the ${type} as your hands graze its FUR.`,
        `The ${type} arches its back, inviting your caress.`,
        `You sense a deep, primal connection as the ${type} leans in.`,
        `The ${type} lets out a low, inviting growl as you approach.`,
        `Your touch elicits a soft moan from the ${type}.`,
        `The ${type} wraps itself around you, craving your warmth.`,
        `You feel the ${type}'s heartbeat quicken beneath your fingertips.`,
        `The ${type} gazes at you with smoldering intensity.`,
        `A playful nip from the ${type} sends a thrill through you both.`,
        `The ${type} trembles with anticipation as you draw closer.`,
        `You and the ${type} share a lingering, intimate moment.`,
        `The ${type} presses its lips to yours in a heated embrace.`,
        `A wave of desire passes between you and the ${type}.`,
        `The ${type} melts into your arms, surrendering to your touch.`,
        `You lose yourself in the ${type}'s passionate gaze.`,
        `The ${type} purrs deeply, inviting you to explore further.`
    ],
    playerFlirtHostileEnemy: (type, gender, plural = false) => {
        // Flirting with a hostile enemy: tension, cracks in their hostility, reluctant enjoyment
        const lines = [
            `You meet the hostile ${type}'s gaze, a daring smile on your lips. GENDER1 tries to look tough, but a smirk betrays GENDER3 amusement.`,
            `You brush your fingers along the ${type}'s arm, and GENDER1 stiffens—yet you catch a hint of shyness in GENDER2 eyes.`,
            `With a teasing grin, you lean in and whisper something that makes the ${type} bite back a smile.`,
            `You press close, letting your breath tickle the ${type}'s ear. GENDER1 pretends not to care, but you see a faint blush.`,
            `A playful wink and a gentle touch make the ${type} roll GENDER2 eyes, but GENDER1 can't hide a pleased grin.`,
            `You lock eyes with the ${type}, and for a moment, GENDER1's guard drops—just enough for you to see a flicker of warmth.`,
            `You let your hand linger on the ${type}'s side, and GENDER1 huffs, but doesn't pull away.`,
            `You murmur a sultry taunt, and the ${type} tries to scoff, but GENDER1's lips twitch with reluctant delight.`,
            `You draw the ${type} near, feeling GENDER1's resistance melt into a playful shove.`,
            `You press your body close, and the ${type} grumbles, but GENDER1's tail gives an involuntary wag.`,
            `You whisper something daring, and the ${type} snorts, but GENDER1's ears flick with interest.`,
            `You trail your fingers along the ${type}'s jaw, and GENDER1's eyes narrow, but a smile tugs at GENDER2 lips.`,
            `You lean in, your breath warm, and the ${type} tries to glare, but GENDER1's cheeks flush.`,
            `You tease the ${type} with a compliment, and GENDER1 scoffs, but can't hide a pleased look.`,
            `You nudge the ${type} playfully, and GENDER1 shoves back, but laughter escapes.`,
            `You let your hand rest on the ${type}'s chest, and GENDER1's heartbeat quickens despite GENDER4 efforts to hide it.`,
            `You murmur a secret, and the ${type} pretends not to listen, but GENDER1 leans closer.`,
            `You brush your lips near the ${type}'s ear, and GENDER1 shivers, trying to play it cool.`,
            `You compliment the ${type}'s strength, and GENDER1 puffs up, but a bashful grin slips through.`,
            `You catch the ${type} watching you, and when your eyes meet, GENDER1 quickly looks away, flustered.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    playerFlirtNonhostileEnemy: (type, gender, plural = false) => {
        // Flirting with a non-hostile enemy: curiosity, playfulness, gentle tension
        const lines = [
            `You offer the ${type} a warm smile, stepping closer as GENDER1 blushes softly.`,
            `You gently brush your hand along the ${type}'s fur, making GENDER3 shiver with anticipation.`,
            `A playful compliment makes the ${type} giggle, GENDER1 clearly enjoying your attention.`,
            `You lean in, your words soft and inviting, and the ${type} can't help but smile.`,
            `You lock eyes with the ${type}, your gaze lingering as GENDER1 looks away bashfully.`,
            `You let your fingers entwine with the ${type}'s, feeling a spark pass between you.`,
            `You whisper a sweet secret, making the ${type} perk up with interest.`,
            `You draw the ${type} into a gentle embrace, GENDER1 relaxing in your arms.`,
            `You trail a soft kiss along the ${type}'s cheek, earning a delighted sigh.`,
            `You share a quiet laugh, the air between you charged with possibility.`,
            `You nuzzle the ${type}'s neck, and GENDER1 giggles, leaning into your touch.`,
            `You compliment the ${type}'s eyes, and GENDER1 beams with pride.`,
            `You playfully bump shoulders with the ${type}, and GENDER1 laughs, bumping you back.`,
            `You whisper a joke, and the ${type} bursts into laughter, GENDER1's tail wagging.`,
            `You brush a stray lock of fur from the ${type}'s face, and GENDER1 smiles shyly.`,
            `You offer your hand, and the ${type} takes it, fingers squeezing yours gently.`,
            `You share a secret glance, and GENDER1's cheeks flush with excitement.`,
            `You tease the ${type} with a flirty remark, and GENDER1 grins, clearly enjoying the attention.`,
            `You lean in for a playful peck, and the ${type} returns it with a bashful giggle.`,
            `You and the ${type} share a moment of quiet closeness, the world fading away.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    playerFlirtAlly: (name, gender, plural = false) => {
        // Flirting with an ally: trust, affection, shared history
        const lines = [
            `You catch ${name}'s eye and flash a mischievous grin, making GENDER1 laugh.`,
            `You lean against ${name}, your touch familiar and welcome.`,
            `A whispered joke in ${name}'s ear makes GENDER1 blush and nudge you playfully.`,
            `You entwine your fingers with ${name}'s, sharing a moment of quiet affection.`,
            `You press your lips to ${name}'s cheek, feeling GENDER2 warmth radiate back.`,
            `You share a lingering look with ${name}, memories and feelings passing unspoken between you.`,
            `You draw ${name} close, your arms wrapping around GENDER3 in a gentle hug.`,
            `You tease ${name} with a playful wink, earning a soft laugh.`,
            `You rest your head on ${name}'s shoulder, feeling safe and content.`,
            `You and ${name} share a private smile, the bond between you clear to anyone watching.`,
            `You ruffle ${name}'s hair, and GENDER1 grins, swatting your hand away playfully.`,
            `You whisper a compliment, and ${name} beams with pride.`,
            `You bump hips with ${name}, and GENDER1 laughs, bumping you back.`,
            `You share a secret glance, and GENDER1's cheeks flush with affection.`,
            `You offer your hand, and ${name} squeezes it gently.`,
            `You nuzzle into ${name}'s neck, and GENDER1 giggles, hugging you tighter.`,
            `You share a silly inside joke, and both of you burst into laughter.`,
            `You lean in for a playful peck, and ${name} returns it with a bashful smile.`,
            `You and ${name} share a moment of quiet closeness, the world fading away.`,
            `You rest your forehead against ${name}'s, savoring the warmth between you.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },

    // === Ally Actions Against Enemies ===
    allyFlirtEnemy: (allyName, enemyName, gender, plural = false) => {
        // Ally flirting with enemy: aquatic, reflective, serene pond-themed
        const lines = [
            `${allyName} emerges gracefully from the pond's edge, water droplets glistening on GENDER3 skin like jewels. GENDER1 approaches ${enemyName} with fluid movements, the setting sun reflecting off the water creating a backdrop of liquid gold.`,
            `${allyName} finds a smooth stone by the water and skips it across the pond's surface, the ripples catching ${enemyName}'s attention. "Each ring is a wish," GENDER1 whispers seductively, "and I'm wishing you'd come closer."`,
            `${allyName} sits on a lily pad near the shore, GENDER3 reflection shimmering in the calm water below. GENDER1 trails GENDER3 fingers through the surface, creating gentle waves while maintaining sultry eye contact with ${enemyName}.`,
            `${allyName} wades gracefully through the shallow water, sending ripples dancing across the pond. GENDER1 pauses to gather water lilies, offering them to ${enemyName} with a smile as radiant as the sun on water.`,
            `${allyName} discovers a secluded cove and beckons ${enemyName} with a mysterious smile. The water laps gently at the shore as GENDER1 settles onto the smooth pebbles, patting the space beside GENDER2 invitingly.`,
            `${allyName} uses the pond's natural amphitheater to GENDER3 advantage, GENDER3 voice carrying beautifully across the water as GENDER1 calls to ${enemyName}. The acoustic magic of the setting makes every word sound like a siren's song.`,
            `${allyName} finds where a stream feeds into the pond and lets the fresh water cascade over GENDER3 hands. GENDER1 offers the cool, clear liquid to ${enemyName}, the intimate gesture framed by cattails and dragonflies.`,
            `${allyName} perches on a fallen log that extends into the water, GENDER3 feet dangling in the pond. GENDER1 kicks playfully, sending sparkles across the surface while giving ${enemyName} a look full of aquatic allure.`,
            `${allyName} swims to the center of the pond where the water is deepest, floating on GENDER3 back with arms spread wide. "The water's perfect," GENDER1 calls to ${enemyName}, "come join me in this liquid embrace."`,
            `${allyName} creates ripples in the shape of a heart with GENDER3 hands, the water carrying the romantic message to where ${enemyName} stands on the shore. The pond itself becomes GENDER3 messenger of desire.`
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },

    allyFeastSuccess: (allyName, enemyType) => [
        `${allyName} uses the pond's deceptive calm to GENDER3 advantage, striking while the ${enemyType} drinks at the water's edge. The brief struggle sends ripples across the surface before ${allyName} claims GENDER3 aquatic victory.`,
        `${allyName} emerges from beneath the lily pads like a predator of the depths, catching the ${enemyType} completely unaware. The hunt ends swiftly in the shallows as ${allyName} drags GENDER3 prize to shore.`,
        `${allyName} drives the ${enemyType} toward the pond's muddy banks where footing becomes treacherous. Unable to escape through the marshy ground, the prey becomes ${allyName}'s well-earned feast.`,
        `${allyName} uses the pond's reflection to confuse the ${enemyType}, striking from an unexpected angle. The water's surface barely has time to settle before ${allyName} emerges triumphant.`,
        `${allyName} corners the ${enemyType} on a small island in the pond's center, the surrounding water cutting off all escape routes. The isolated hunt concludes with ${allyName} satisfying GENDER3 hunger among the reeds.`,
        `${allyName} moves through the water with serpentine grace, the ${enemyType} unable to match GENDER3 aquatic prowess. The pond becomes ${allyName}'s hunting ground as GENDER1 claims another successful feast.`,
        `${allyName} uses the cattails as cover, striking when the ${enemyType} ventures too close to the water. The marshy vegetation witnesses ${allyName}'s predatory success beneath the open sky.`,
        `${allyName} herds the ${enemyType} into the pond's deepest section where they struggle to stay afloat. Taking advantage of their distress, ${allyName} secures GENDER3 meal among the gentle waves.`
    ],

    allyFeastFail: (allyName, enemyType) => [
        `${allyName} lunges from the water at the ${enemyType}, but GENDER3 wet fur weighs GENDER2 down. The prey easily sidesteps the sluggish attack and bounds away across the dry ground to safety.`,
        `${allyName} tries to ambush the ${enemyType} from beneath the surface, but creates too many bubbles. The telltale signs alert the prey, who retreats before ${allyName} can emerge from the water.`,
        `${allyName} pursues the ${enemyType} across the pond, but gets tangled in underwater weeds. By the time GENDER1 breaks free, GENDER3 prey has reached the opposite shore and vanished into the rushes.`,
        `${allyName} attempts to drive the ${enemyType} into the water, but a family of ducks explodes into flight between them. The chaotic flapping of wings allows the prey to escape in the confusion.`,
        `${allyName} strikes from the lily pads, but lands on a particularly bouncy one that launches GENDER2 past the target entirely. The ${enemyType} watches in confusion before fleeing the waterside.`,
        `${allyName} corners the ${enemyType} by the shore, but slips on the muddy bank at the crucial moment. GENDER3 undignified tumble into the water gives the prey time to escape across dry land.`,
        `${allyName} tries to use the pond's acoustics to confuse the ${enemyType}, but GENDER3 call echoes back louder than expected. The startling sound frightens both predator and prey, ruining the hunt.`
    ],

    allyFeedSuccess: (allyName, enemyType) => [
        `${allyName} gathers sweet pond berries growing along the shore and offers them to the ${enemyType} with cupped hands. The water's gentle lapping provides a peaceful soundtrack to this act of kindness.`,
        `${allyName} finds the clearest, coolest water from a hidden spring and shares it with the thirsty ${enemyType}. This gift of pure refreshment beside the tranquil pond creates instant trust and friendship.`,
        `${allyName} weaves a crown of water lilies and cattail fronds, placing it gently on the ${enemyType}'s head. The aquatic crown glistens with dewdrops, winning over the creature's heart completely.`,
        `${allyName} demonstrates the pond's safety by floating peacefully on GENDER3 back, showing the ${enemyType} that all threats have passed. The serene water reflection convinces them to join your group.`,
        `${allyName} collects smooth river stones and teaches the ${enemyType} to skip them across the pond's surface. The shared joy of watching ripples spread creates a bond of lasting friendship.`,
        `${allyName} discovers a patch of edible water plants and shares their knowledge freely with the ${enemyType}. The generous lesson about the pond's hidden bounty proves GENDER3 good intentions.`,
        `${allyName} finds where fish gather in the shallows and invites the ${enemyType} to watch them swim. The peaceful moment by the water's edge builds trust through shared wonder.`,
        `${allyName} shows the ${enemyType} how to read the pond's moods - where the water runs clear, which plants are safe. This aquatic wisdom shared freely creates deep understanding between them.`
    ],

    allyFeedFail: (allyName, enemyType) => [
        `${allyName} offers pond berries to the ${enemyType}, but they've gone sour from too much water. The bitter taste sends the ${enemyType} spitting and fleeing back to drier, safer ground.`,
        `${allyName} tries to impress the ${enemyType} with GENDER3 swimming skills, but belly-flops spectacularly instead. The undignified splash and resulting muddy water leave the ${enemyType} thoroughly unimpressed.`,
        `${allyName} attempts to share the pond's peace with the ${enemyType}, but steps on a snapping turtle. GENDER3 yelp of pain and frantic dance disrupts the tranquil atmosphere completely.`,
        `${allyName} gathers beautiful water lilies for the ${enemyType}, but disturbs a nest of angry frogs in the process. The cacophony of croaking and splashing ruins any chance of peaceful communication.`,
        `${allyName} tries to demonstrate water safety to the ${enemyType}, but a large fish jumps unexpectedly, soaking them both. The cold, muddy surprise kills any romantic or friendly mood.`,
        `${allyName} offers to teach the ${enemyType} stone-skipping, but GENDER3 first throw hits a sleeping heron. The bird's indignant squawking and aggressive dive-bombing sends both creatures fleeing.`,
        `${allyName} attempts to create atmosphere by singing across the water, but GENDER3 voice cracks embarrassingly on the high notes. The ${enemyType} takes this as a sign to seek better company elsewhere.`
    ],

    allyFuckSuccess: (allyName, enemyType, gender, plural = false) => [
        `${allyName} and the ${enemyType} find a secluded cove where the water laps gently at smooth stones. Surrounded by the pond's tranquil embrace, they explore their desires both in and out of the warm, shallow water.`,
        `${allyName} leads the ${enemyType} to a bed of soft moss beside a hidden spring. The gentle bubbling provides nature's soundtrack as they connect intimately, the clear water reflecting their passion.`,
        `${allyName} and the ${enemyType} discover each other on a lily pad platform, the pond's surface supporting their tender encounter. Their union sends gentle ripples across the water, witnessed only by dragonflies.`,
        `${allyName} creates a bower of cattails and water reeds for GENDER3 and the ${enemyType} to share. In this aquatic sanctuary, they find pleasure while the pond keeps their secrets beneath its calm surface.`,
        `${allyName} and the ${enemyType} wade into the warm shallows, their bodies intertwining like the currents around them. The water's embrace enhances their connection, making every touch electric.`,
        `${allyName} guides the ${enemyType} to where a waterfall feeds the pond, the cascade creating a natural curtain of privacy. Behind this liquid veil, they share passion that flows as freely as the water.`,
        `${allyName} and the ${enemyType} float together in the pond's center, their coupling as fluid and natural as the water supporting them. The stars reflect in the ripples they create together.`,
        `${allyName} shows the ${enemyType} a grotto where the water glows with phosphorescence. In this magical aquatic chamber, their intimate dance creates trails of light in the luminous pond.`
    ],

    allyFuckFail: (allyName, enemyType) => [
        `${allyName} and the ${enemyType} settle beside the romantic pond, but a beaver dam bursts upstream, sending a rush of cold water that soaks them both and completely ruins the mood.`,
        `${allyName} tries to create intimacy on a lily pad, but it can't support both their weights. They tumble into the water with an ungraceful splash, destroying any romantic atmosphere.`,
        `${allyName} and the ${enemyType} begin to connect by the water's edge, but disturb a muskrat family. The territorial rodents chase them away from the pond with aggressive chittering.`,
        `${allyName} attempts to seduce the ${enemyType} with graceful swimming, but gets caught in pond weeds. GENDER3 frantic struggle to get free looks anything but attractive to the watching ${enemyType}.`,
        `${allyName} and the ${enemyType} find a cozy spot, but it turns out to be directly downwind from a stagnant part of the pond. The unpleasant smell makes romance absolutely impossible.`,
        `${allyName} tries to create atmosphere by calling across the water, but attracts every frog in the pond instead. The deafening chorus of croaks drowns out any chance of intimate conversation.`,
        `${allyName} and the ${enemyType} settle onto what seems like a comfortable bank, but it's actually home to a family of very territorial turtles who defend their territory vigorously.`
    ],

    furryInterested: (type) => [
        `The ${type} seems interested...`,
        `You notice a spark of curiosity in its eyes.`,
        `It appears intrigued by you.`,
        `The ${type} tilts its head, watching you closely.`,
        `A soft sound escapes the ${type} as it draws nearer.`,
        `You catch the ${type} glancing at you repeatedly.`,
        `It circles you, sniffing the air with interest.`,
        `The ${type}'s EARS perk up as you approach.`,
        `You sense the ${type}'s attention is fixed on you.`,
        `It takes a cautious step in your direction.`,
        `The ${type}'s TAIL flicks with anticipation.`,
        `You see the ${type}'s NOSE twitch as it studies you.`,
        `It sits down, waiting to see what you'll do next.`,
        `The ${type}'s eyes follow your every movement.`,
        `It lets out a curious chirp or grunt.`,
        `You feel the ${type}'s gaze linger on you.`,
        `It edges closer, clearly wanting to learn more.`,
        `The ${type} sniffs at your hand, testing your scent.`,
        `It gives a tentative wag or purr.`,
        `You notice the ${type}'s body language relax slightly.`
    ],
    feastSuccess: (type, gain) => [
        `You feast on the ${type} and gain ${gain} hunger!`,
        `Devouring the ${type} restores ${gain} hunger!`,
        `You consume the ${type}, replenishing ${gain} hunger.`,
        `You open wide and swallow the ${type} whole, feeling your hunger fade as it settles inside.`,
        `The ${type} squirms as you gulp it down, your belly growing fuller with every swallow.`,
        `With a deep breath, you engulf the ${type}, its struggles fading as you digest it for ${gain} hunger.`,
        `You savor the sensation as the ${type} slides down your throat, nourishing you from within.`,
        `The ${type} vanishes into your MAW, leaving you satisfied and energized.`,
        `You feel the ${type} wriggle as it descends, your hunger replaced by a pleasant fullness.`,
        `A powerful gulp sends the ${type} into your stomach, where it fuels your strength.`,
        `You relish the fullness as the ${type} is safely tucked away inside you.`,
        `The ${type} is enveloped by your body, its energy becoming your own.`,
        `You pat your belly contentedly after swallowing the ${type} whole.`,
        `The ${type} disappears past your lips, and you feel a surge of vitality.`,
        `You draw the ${type} in, your hunger quickly fading as you digest your living meal.`,
        `The ${type} is helpless as you swallow it, your body eagerly absorbing its energy.`,
        `You gulp down the ${type}, feeling it settle and your hunger vanish.`,
        `A deep sense of satisfaction washes over you as the ${type} is vored alive.`,
        `You feel the ${type} moving inside for a moment before your hunger is fully sated.`,
        `The ${type} is drawn into your stomach, its presence fueling your recovery.`,
        `You finish your meal, the ${type} now a part of you, and your hunger gone.`,
        `You swallow the ${type} in one smooth motion, feeling stronger immediately.`,
        `The ${type} is enveloped by your MAW, and you feel your hunger melt away.`,
        `You savor the living meal, the ${type} nourishing you as it disappears inside.`,
        `You feel the ${type}'s energy flow into you as you finish your feast.`,
        `The ${type} is gone, leaving you feeling full and revitalized.`,
        `You take a moment to enjoy the sensation as the ${type} is digested alive.`,
        `You feel your strength return as the ${type} is absorbed within you.`,
        `The ${type} is swallowed whole, and you feel completely satisfied.`
    ],
    feastFail: (type) => [
        `Your feast attempt fails.`,
        `You fail to satisfy your hunger.`,
        `The ${type} slips from your grasp.`,
        `You miss your chance to swallow the ${type}.`,
        `Your prey escapes before you can feast.`,
        `You fumble and lose the ${type}.`,
        `Your hunger remains as the ${type} wiggles out of your PAWS.`,
        `You bite down, but the ${type} wriggles free.`,
        `You hesitate, and the opportunity is lost.`,
        `You can't quite manage to eat the ${type} this time.`,
        `Your MAW snaps shut on empty air.`,
        `You lunge, but your ${type} gets away.`,
        `You try to feast on the ${type}, but you fail.`,
        `You lose your grip and the ${type} escapes.`,
        `Your attempt is thwarted by a sudden movement.`,
        `You are left hungry as your ${type} flees.`,
        `You feel frustration as the ${type} dodges your grasp.`,
        `You watch helplessly as the ${type} slips away.`,
        `Your belly gurgles as you fail to swallow the ${type}.`,
        `${type} escapes your grasp at the last moment.`
    ],
    recruitSuccess: (type) => [
        `You successfully recruit the ${type}!`,
        `The ${type} joins your cause!`,
        `You gain a new ally: the ${type}.`,
        `The ${type} is now part of your team.`,
        `With a nod, the ${type} agrees to follow you.`,
        `The ${type} pledges loyalty to your journey.`,
        `A new friendship is forged with the ${type}.`,
        `The ${type} stands proudly at your side.`,
        `You welcome the ${type} into your ranks.`,
        `The ${type} is eager to help you on your quest.`,
        `A sense of camaraderie grows as the ${type} joins you.`,
        `The ${type} is ready to face challenges with you.`,
        `You feel stronger with the ${type} as your ally.`,
        `The ${type} gives a cheerful nod, ready for adventure.`,
        `The ${type} is happy to be part of your group.`,
        `You and the ${type} share a moment of mutual respect.`,
        `The ${type} is now a trusted companion.`,
        `The ${type} steps forward, accepting your invitation.`,
        `A bond forms as the ${type} joins your side.`,
        `The ${type} is now a valued member of your party.`,
        `You sense the ${type}'s determination to help you succeed.`
    ],
    allyMadeOut: (type, gender, plural = false) => {
        // Use GENDER# placeholders in lines
        const lines = [
            `${type} kisses you passionately, breathless kiss, hands roaming hungrily over each other's bodies.`,
            `${type} presses against your body with lust in GENDER2 eyes, GENDER1 throws you on the ground, and you both make out.`,
            `You both explore each other's body, moans and gasps filling the air.`,
            `You lock paws with ${type}, bodies entwined as you kiss deeply.`,
            `${type} gently pushes you against a tree, kissing you passionately.`,
            `You both pull eachother close, bodies pressed tightly, feeling every curve and muscle as you kiss deeply.`,
            `${type} pulls you to the ground, kissing you passionately.`,
            `You both lean into each other, shivering with anticipation as lips and tongues explore sensitive spots.`,
            `One bites gently at the other's lower lip, drawing a gasp before diving into another passionate kiss.`,
            `You lose yourself in ${type}'s passionate kisses, hands and mouths exploring, breath mingling in the heat.`,
            `Your fingers trace along GENDER2 skin, sending shivers as they press closer, desperate for more contact.`,
            `${type}'s hand slides down, gripping a thigh and pulling their bodies even tighter.`,
            `You both roll on the ground, tangled in limbs and laughter, lips never parting for long.`,
            `A teasing tongue flicks along your lips before diving into a deep, passionate kiss.`,
            `${type}'s kisses grow deeper, more urgent, as hands roam and bodies grind together.`,
            `You both gasp each other's names, lost in the haze of pleasure and longing.`,
            `${type} pins you to the ground, lips trailing down your neck as GENDER2 hands explore boldly.`,
            `You both arch and writhe together, every touch and kiss stoking the fire between you.`,
            `Breathless and flushed, you cling to each other, savoring every heated moment.`,
            `Your bodies move in perfect rhythm, lost in the intensity of your embrace.`,
        ];
        return lines.map(line => applyPronouns(line, gender, plural));
    },
    actionFail: [
        "Your attempt fails.",
        "That didn't work.",
        "You don't manage to pull it off.",
        "You fumble and lose your chance.",
        "Your hands slip at the last moment.",
        "You hesitate, and the opportunity passes.",
        "You try, but nothing happens.",
        "You misjudge your timing and fail.",
        "You lose focus and the action slips away.",
        "You make a mistake and it doesn't work.",
        "You stumble, ruining your attempt.",
        "You can't seem to get it right.",
        "You miss your mark.",
        "You act, but the result is disappointing.",
        "You give it your best, but fall short.",
        "You try again, but still fail.",
        "You are thwarted by bad luck.",
        "You falter and the action fizzles.",
        "You attempt it, but something goes wrong.",
        "You are unable to complete the action."
    ],
    enemyHitPlayer: (type) => [
        `The ${type} hits you with a fierce blow!`,
        `You are struck by the ${type}, pain radiating through your body!`,
        `Ouch! The ${type}'s attack leaves you reeling.`,
        `A sudden blow from the ${type} knocks you off balance!`,
        `The ${type} lashes out, forcing you to defend yourself!`,
        `You feel pain as the ${type} attacks relentlessly.`,
        `The ${type}'s attack lands, making you stagger!`,
        `You stagger as the ${type} lands a solid hit.`,
        `A sharp strike from the ${type} makes you wince.`,
        `The ${type} CLAWS at you, tearing at your defenses!`,
        `You wince as the ${type} bites down hard.`,
        `A heavy blow from the ${type} sends you stumbling!`,
        `The ${type} rams into you, knocking the wind from your lungs.`,
        `You are knocked back by the ${type}'s powerful attack.`,
        `The ${type} pounces, pinning you momentarily!`,
        `You feel the sting of the ${type}'s relentless assault.`,
        `A quick swipe from the ${type} leaves a burning pain!`,
        `The ${type} lands a solid hit, your vision blurring for a moment.`,
        `You are wounded by the ${type}, struggling to stay upright.`,
        `The ${type} strikes fiercely, your strength faltering.`,
        `You are battered by the ${type}'s unyielding assault.`
    ],
    enemyHitAlly: (type, name) => [
        `The ${type} hits ${name} with a fierce blow!`,
        `${name} is struck by the ${type}, reeling from the impact!`,
        `${name} is knocked back by the ${type}'s attack!`,
        `${name} takes a blow from the ${type}, struggling to stay upright!`,
        `A fierce attack from the ${type} leaves ${name} staggering!`,
        `${name} is wounded by the ${type}, faltering in the fight!`,
        `The ${type} CLAWS at ${name}, tearing at their defenses!`,
        `${name} winces as the ${type} lands a solid hit.`,
        `A sudden strike from the ${type} leaves ${name} off balance.`,
        `${name} is battered by the ${type}, barely holding on!`,
        `The ${type} bites down on ${name}, making them cry out!`,
        `${name} is knocked back by the ${type}'s powerful attack!`,
        `A heavy blow from the ${type} leaves ${name} hurt and dazed.`,
        `${name} is caught off guard and takes a punishing hit from the ${type}.`,
        `The ${type} pounces on ${name}, pinning them momentarily!`,
        `${name} suffers under the ${type}'s relentless assault!`,
        `A quick swipe from the ${type} leaves ${name} scrambling to recover!`,
        `${name} staggers as the ${type} delivers a crushing blow!`,
        `The ${type} rams into ${name}, sending them sprawling!`,
        `${name} is wounded by a sudden attack from the ${type}, struggling to regain composure!`
    ],
    enemyFled: (type) => [
        `The ${type} fled!`,
        `The ${type} escapes into the distance!`,
        `With a quick dash, the ${type} is gone.`,
        `The ${type} vanishes into the undergrowth.`,
        `You watch as the ${type} disappears from sight.`,
        `The ${type} bolts away, leaving you behind.`,
        `A flash of movement, and the ${type} is gone.`,
        `The ${type} retreats hastily, not looking back.`,
        `You see only a blur as the ${type} flees.`,
        `The ${type} darts away, evading your grasp.`,
        `The ${type} slips away before you can react.`,
        `You lose sight of the ${type} as it escapes.`,
        `The ${type} sprints off, quickly out of reach.`,
        `A rustle in the brush marks the ${type}'s escape.`,
        `The ${type} makes a hasty retreat.`,
        `You hear the sound of the ${type} running away.`,
        `The ${type} vanishes between the trees.`,
        `The ${type} flees, leaving only footprints behind.`,
        `You catch a glimpse of the ${type} as it disappears.`,
        `The ${type} runs for safety, not daring to look back.`
    ],
    enemyFleeFail: (type) => [
        `The ${type} tried to flee but failed.`,
        `The ${type} attempts escape and stumbles!`,
        `Escape fails for the ${type}.`,
        `The ${type} tries to run but is blocked!`,
        `The ${type} makes a break for it, but can't get away.`,
        `The ${type} darts to the side, but you cut it off.`,
        `The ${type} hesitates and loses its chance to escape.`,
        `A failed leap leaves the ${type} vulnerable.`,
        `The ${type} slips but can't get away in time.`,
        `The ${type} turns to flee, but is stopped short.`,
        `The ${type} is too slow and fails to escape.`,
        `The ${type} panics, but can't find a way out.`,
        `The ${type} is cornered and cannot flee.`,
        `The ${type} tries to vanish, but you block its path.`,
        `The ${type} is trapped and its escape fails.`,
        `The ${type} looks for an exit, but finds none.`,
        `The ${type} is thwarted in its attempt to flee.`,
        `The ${type} makes a desperate dash, but is caught.`,
        `The ${type} is forced to stay and fight.`,
        `The ${type} freezes, unable to escape.`
    ],
    playerFleeFail: (type) => [
        `Failed to flee!`,
        `You can't get away!`,
        `Your escape attempt is thwarted.`,
        `You try to run, but the ${type} blocks your path.`,
        `You stumble and lose your chance to escape.`,
        `You hesitate, and the ${type} closes in.`,
        `You turn to flee, but your legs won't move.`,
        `A sudden obstacle stops you from escaping.`,
        `You dash for safety, but are forced back.`,
        `You slip and fall, unable to get away.`,
        `Your path is blocked and you can't escape.`,
        `You make a break for it, but are intercepted.`,
        `You freeze in fear and fail to flee.`,
        `You try to slip away, but are spotted instantly.`,
        `You attempt to retreat, but the way is shut.`,
        `You are too slow and the ${type} catches up.`,
        `You look for an exit, but find none.`,
        `You try to vanish into the shadows, but are seen.`,
        `You dart to the side, but are cut off.`,
        `You attempt to escape, but your efforts are in vain.`
    ],
};

function narrateTile(tile) {
    const lines = NarratorLines.tile[tile];
    if (Array.isArray(lines) && lines.length > 0) {
        const line = lines[Math.floor(Math.random() * lines.length)];
        updateNarrator(line);
    }
}
export default NarratorLines;